/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "dir.h"
#include <dirent.h>

extern int errno;

readdir_res * readdir_1_svc(nametype dirname,  struct svc_req *rqstp){
	static readdir_res result;
	DIR *dirp;
	struct dirent *d;
	namelist nl;
	namelist *nlp;


	dirp = opendir(dirname);
	if(dirp == (DIR *) NULL){
		result.errno = errno;
		return &result;
	}
	/*
	 * La siguiente línea de código libera la memoria que se asigno (para el
	 * resultado) en una ejecución previa del servidor.
	 */
	xdr_free(xdr_readdir_res, &result);

	nlp = &result.readdir_res_u.list;
	while(d = readdir(dirp)){
		nl = *nlp = (namenode *) malloc(sizeof(namenode));
		if(nl == (namenode *) NULL){
			result.errno = 10;
			closedir(dirp);
			return &result;
		}
		nl->name = strdup(d->d_name);
		nlp = &nl->next;
	}
	*nlp = (namelist)NULL;
	result.errno = 0;
	closedir (dirp);
	return &result;
}
