/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DNS_H_RPCGEN
#define _DNS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct dns_1_registrar_1_argument {
	char *nombre;
	char *ip;
};
typedef struct dns_1_registrar_1_argument dns_1_registrar_1_argument;

#define DNS_1 0x20000001
#define DNSV1 1

#if defined(__STDC__) || defined(__cplusplus)
#define dns_1_buscar 1
extern  char ** dns_1_buscar_1(char *, CLIENT *);
extern  char ** dns_1_buscar_1_svc(char *, struct svc_req *);
#define dns_1_registrar 2
extern  char ** dns_1_registrar_1(char *, char *, CLIENT *);
extern  char ** dns_1_registrar_1_svc(char *, char *, struct svc_req *);
#define dns_1_borrar 3
extern  char ** dns_1_borrar_1(char *, CLIENT *);
extern  char ** dns_1_borrar_1_svc(char *, struct svc_req *);
extern int dns_1_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define dns_1_buscar 1
extern  char ** dns_1_buscar_1();
extern  char ** dns_1_buscar_1_svc();
#define dns_1_registrar 2
extern  char ** dns_1_registrar_1();
extern  char ** dns_1_registrar_1_svc();
#define dns_1_borrar 3
extern  char ** dns_1_borrar_1();
extern  char ** dns_1_borrar_1_svc();
extern int dns_1_1_freeresult ();
#endif /* K&R C */

struct dns_2_registrar_1_argument {
	char *nombre;
	char *ip;
};
typedef struct dns_2_registrar_1_argument dns_2_registrar_1_argument;

#define DNS_2 0x20000002
#define DNSV2 1

#if defined(__STDC__) || defined(__cplusplus)
#define dns_2_buscar 1
extern  char ** dns_2_buscar_1(char *, CLIENT *);
extern  char ** dns_2_buscar_1_svc(char *, struct svc_req *);
#define dns_2_registrar 2
extern  char ** dns_2_registrar_1(char *, char *, CLIENT *);
extern  char ** dns_2_registrar_1_svc(char *, char *, struct svc_req *);
#define dns_2_borrar 3
extern  char ** dns_2_borrar_1(char *, CLIENT *);
extern  char ** dns_2_borrar_1_svc(char *, struct svc_req *);
extern int dns_2_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define dns_2_buscar 1
extern  char ** dns_2_buscar_1();
extern  char ** dns_2_buscar_1_svc();
#define dns_2_registrar 2
extern  char ** dns_2_registrar_1();
extern  char ** dns_2_registrar_1_svc();
#define dns_2_borrar 3
extern  char ** dns_2_borrar_1();
extern  char ** dns_2_borrar_1_svc();
extern int dns_2_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_dns_1_registrar_1_argument (XDR *, dns_1_registrar_1_argument*);
extern  bool_t xdr_dns_2_registrar_1_argument (XDR *, dns_2_registrar_1_argument*);

#else /* K&R C */
extern bool_t xdr_dns_1_registrar_1_argument ();
extern bool_t xdr_dns_2_registrar_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_DNS_H_RPCGEN */
