/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

/*
 * Compilar con make -f Makefile.msg
 * Ejecutar con ./msg_client localhost <mensaje>
 */

#include "msg.h"
#include <stdio.h>

/**************************************************************************/

void messageprog_1(char *host, char *msg) {
	CLIENT *clnt;
	int  *result_1;
	char *printmessage_1_arg1 = msg;

	/* Crea estructura de datos del proceso cliente para el servidor designado */
	#ifndef	DEBUG
		clnt = clnt_create (host, MESSAGEPROG, PRINTMESSAGEV1, "udp");
		if (clnt == NULL) {
			/* No se pudo establecer la conexión con el servidor */
			clnt_pcreateerror (host);
			exit (1);
		}
	#endif	/* DEBUG */

		/* Llamada remota al procedimiento del sevidor */
		result_1 = printmessage_1(printmessage_1_arg1, clnt);
		if (result_1 == (int *) NULL) {
			/* Ocurrió un error durane la llamada al servidor */
			clnt_perror (clnt, "call failed");
			exit (1);
		}

		/* El servidor fue incapaz de imprimir el mensaje */
		if (*result_1 == 0){
			fprintf(stderr, "%s: no pudo imprimir el mensaje\n", host);
			exit (1);
		}

		printf("Mensaje enviado a %s\n", host);

	#ifndef	DEBUG
		clnt_destroy (clnt);
	#endif	 /* DEBUG */
	exit (0);
}

/**************************************************************************/

int main (int argc, char *argv[]) {
	char *host;
	char *msg;

	if (argc != 3) {
		fprintf (stderr, "usage: %s <server_host> <message>\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	msg	 = argv[2];

	messageprog_1 (host, msg);
	exit (0);
}
