/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

 /*
  * Compilar con make -f Makefile.msg
  * Ejecutar con ./msg_server
  */

#include "msg.h"
#include <stdio.h>

int * printmessage_1_svc(char *arg1,  struct svc_req *rqstp) {
	static int  result;

	/*
	 * Server code
	 */
	FILE *f;
	f = fopen("./Servidor", "w");
	if (f == (FILE *) NULL){
		result = 0;
	  return &result;
	}
	fprintf(f, "%s\n", arg1);
	fclose(f);
	result = 1;
	return &result;
}
