/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "DNS.h"

bool_t
xdr_registrar_1_argument (XDR *xdrs, registrar_1_argument *objp)
{
	 if (!xdr_string (xdrs, &objp->nombre, ~0))
		 return FALSE;
	 if (!xdr_string (xdrs, &objp->ip, ~0))
		 return FALSE;
	return TRUE;
}
