/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "DNS.h"

typedef struct Equipo {
  char *nombre;
  char *ip;
};

typedef struct Red {
  char nombre[15];
  struct Equipo equipos_en_red[10];
  int equipos_conectados;
};

struct Red mi_red = {"DNS-1", {}, 0};

/******************************************************************************/
/**
 * Función de inicialización del strucy mi_red
 * Utilizada como función externa en el main del servidor
 */
void init (void) {
  struct Equipo tw	= {"twitter.com",	"104.244.42.129" };
  struct Equipo yt	= {"youtube.com",	"172.217.9.238"	 };
  struct Equipo gg 	= {"google.com",	"172.217.3.110"	 };

  mi_red.equipos_en_red[0] = tw;
  mi_red.equipos_en_red[1] = yt;
  mi_red.equipos_en_red[2] = gg;
  mi_red.equipos_conectados = 3;
}

/******************************************************************************/

int _buscar (char *nombre) {
  for (int i=0; i<mi_red.equipos_conectados; i++)
		if ( strcmp(nombre, mi_red.equipos_en_red[i].nombre) == 0)
			return i;

  return -1;
}

/******************************************************************************/

char ** dns_1_buscar_1_svc(char *nombre,  struct svc_req *rqstp) {
	static char * result;
  int index;

  result = (char *) malloc(50);

	result = "Domain Name Not Found!";

	index = _buscar(nombre);
  if (index != -1)
    result = mi_red.equipos_en_red[index].ip;

	return &result;
}

/******************************************************************************/

char ** dns_1_registrar_1_svc(char *nombre, char *ip,  struct svc_req *rqstp) {
	static char * result;

  if ( _buscar(nombre) != -1 ){
    result = "[ERROR] Domain Name Already Exists";
    return &result;
  }

  result = (char *) malloc(50);
  mi_red.equipos_en_red[mi_red.equipos_conectados].nombre = malloc(sizeof(*nombre));
  mi_red.equipos_en_red[mi_red.equipos_conectados].ip = malloc(sizeof(*ip));

	// Insertar datos del equipo
	strcpy(mi_red.equipos_en_red[mi_red.equipos_conectados].nombre, nombre);
	strcpy(mi_red.equipos_en_red[mi_red.equipos_conectados].ip, ip);

	// Comprobar integridad de los datos
	if ( strcmp(nombre, mi_red.equipos_en_red[mi_red.equipos_conectados].nombre) != 0)
		result = "[ERROR] Domain Name couldn't be saved.";
	else if ( strcmp(ip, mi_red.equipos_en_red[mi_red.equipos_conectados].ip) != 0)
		result = "[ERROR] IP address couldn't be saved.";
	else
		result = "Success.";

	// Actualizar el contador de equipos conectados
	mi_red.equipos_conectados++;

	return &result;
}

/******************************************************************************/

char ** dns_1_borrar_1_svc(char *nombre,  struct svc_req *rqstp) {
	static char * result;
  int index;

  index = _buscar(nombre);

  if ( index == -1 ){
    result = "[ERROR] Domain Name Not Found";
    return &result;
  }

  result = (char *) malloc(50);

  for(int i=index; i<mi_red.equipos_conectados-1; i++){
    mi_red.equipos_en_red[i] = mi_red.equipos_en_red[i+1];
  }

  mi_red.equipos_conectados--;
  result = "Delete Successful";

	return &result;
}
